### ISSUE TITLE
Invalid key vs valid nil response differentiation impossible via ResultMap interface

### ISSUE THREAD

**Issue by fungl164** [andy9775/dataloader#1]
It is currently not possible to differentiate between a dataloader key that was never requested/processed vs a valid nil response from a user-defined batch function.  

Allowing the ```ResultMap interface``` to return a ```*Result``` would take this into account for this use case.

Many thanks for this!  Currently testing...

**Comment by andy9775** [comment]
Hey, @fungl164 thanks for the feedback and sorry for the delayed response. 

Can you be a bit more specific as to what you're trying to achieve? I think I see what your saying but I want to make sure we're on the same page

**Comment by fungl164** [comment]
@andy9775 I forget the exact circumstances, but it may have been during my early attempts to understand how the package worked.  I was manually constructing resultmaps and then checking over the results not by asking for the resultmap keyset but by asking from a cached set of keys I was keeping.

Because the resultmap interface requires a Result struct to be returned, any missed key (even if not existent) will return a proper Result struct.  This makes it hard to determine whether it's a valid nil result or one that should have never been there.

In my case, I was delivering results that were nil, but should have been excluded from my response.  I just couldn't tell a real Result vs an "invalid key" that should have been ignored.  My problem, not yours...but it took me a while to figure out. : /

Anyway, looking through the code I see this happening is because the resultmap look up eats up the ok when searching for is an invalid key within its inner map before returning.  

There are two possible fixes as I see it:
1. Return the ok along with the result, or 
2. Force a pointer to be returned.  

Either way it requires an API change in case you wanted to ensure any downstream issues arising from this subtle misuse of the resultmap queries go cleanly away. : )

Let me know if any of what im saying here is unclear...

Thnks for responding! : )

**Comment by andy9775** [comment]
I see what you're saying, good catch. I think I originally had a `map[string]interface{}` which is why the ok was swallowed.

I'll opt to return the ok, I think.

**Comment by andy9775** [comment]
@fungl164 should be addressed now. Let me know if you run into any other issues

**Comment by fungl164** [comment]
Awesome! will do. Thnxs!
